version: '3.1'


services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  test-db:
    container_name: test-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.0
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper