version: '3.1'


services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  test-db:
    container_name: test-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5433:5432